name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    # Build the backend
    - name: Build Backend
      run: |
        cd Backend/MyOAuthAPI
        dotnet build

    # Setup Node.js for Angular frontend
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: v22

    # Build the frontend
    - name: Build Frontend
      run: |
        cd Frontend/MyOAuthApp
        npm install
        npm run build
